exports.formError = {
    emptyEmail: "Veuillez entrer votre Email",
    emptyPassword: "Veuillez entrer votre mot de passe",
    invalidPhone: "Numero de telephone invalide",
    positionTooLong: "position tres longue",
    email: "Veuilez entrer une adress e-mail correcte",
    isAuth: "Accès refusé",
    isUser: "Admin Resource, Accès refusé !",
    checkThisEmailIfAlreadyExist: "cette email déjà exist",
    passwordAndConfirmPasswordIsMatch: "Les mots de passe saisis ne sont pas identiques.",
    checkThisEmailIfNotExist: "Ce compte n'existe pas ! Veuillez-vous inscrire",
    invalidUserPassword: "Veuillez entrer un mot de passe correct",
    disconnected: "Vous êtes déconnecté",
    validCurrentPassword: "Le mot de passe actuel saisi est incorrect",
    updatedPassword: "le mot de pass a été modifiée",
    invalidCert: "Invalid private cert",
    Unauthorized: "Non autorisé",
    Disconnected: "Disconnected",
    
}
